### ISSUE TITLE
Lab 4 não está no GitHub

### ISSUE THREAD

**Issue by martim-lusofona** [EnricoFerreira22308720/EnricoFerreira22308720.github.io#6]
![image](https://github.com/user-attachments/assets/2fceee4a-18d4-4c75-af21-3fe2c1fea108)

Faltou fazer commit e push das alterações.

**Comment by EnricoFerreira22308720** [comment]
Me desculpe professor acabou dando erro de merge e nao tinha visto agora acredito estar certo e desculpa o atraso

**Comment by EnricoFerreira22308720** [comment]
@martim-lusofona
